extra = {"join": 
         ["Don't mind if I do!",
          "I've actually been wanting to play Uno for a while!",
          "Only joining because I know your don't mind getting your ass beat!",
          "No fooling around.",
          "I better not catch you cheating.",
          "This game is the only thing I love more than ice cream... Other than my wife of course.",
          "Uno! Oh, Too early? Sorry... I was just forseeing my victory.",
          "8 wild cards in the whole deck and I'm going to be holding 7 of them at the start!",
          "Will I win?... Stupid question. The answer is always yes.",
          "I can already smell the victory."],
         "loss": 
         ["Aww chucks... I'll win next time.",
          "You just got really lucky, kid.",
          "Pft, I let you win that one.",
          "I'm was just a little tired, that's all.",
          "It's just one game.",
          "This never happens.",
          "A broken clock is great twice a day.",
          "I was distracted.",
          "Fine, you can have this one.",
          "Shame.",
          "You've won this battle, but not the war.",
          "Must have been rigged."],
         "win": 
         ["That was a good game! Lots of fun. Hope to play again sometime soon.",
          "Who's surprised? Not me.",
          "I think I deserve ice cream as a little treat.",
          "This is exactly what I love about this game.",
          "See how great I am?",
          "This is just how it is.",
          "I'm on top of the food chain!",
          "You can try 10 more times, but you still won't win.",
          "I don't need any praise or claps, I know I'm great.",
          "And my undefeated streak continues."],
         "trivia": 
         ["Sometimes, I go out to the park and play Uno with strangers. Sometimes they're pleasant, sometimes not...",
          "I went to college for 4 years to become a teacher in literature. I love the kids I teach, but sometimes I think I should have picked a different major.",
          "I've found that Uno is the best game to bond over. That's if you aren't arguing with the people you're playing against.",
          "My wife isn't a big fan of this game, but from time to time she plays with me because of how much I love it. She's nice.",
          "I've been struggling with family drama lately. Sometimes I wonder if it's even worth the hassle of keeping up with people that you don't need.",
          "I was born the same year as Uno, 1971, but I didn't discover it until I was about 15. Before Uno, television used to keep my company.",
          "From what I hear from my kids, high school today seems to be so different from when I used to go, yet it's still so similar.",
          "Both of my daughters hate this game, but I'm hoping they start liking it once they're a little older.",
          "As a kid, I used to dream about becoming a movie star, nowadays I don't dream anymore.",
          "Every year I find it harder and harder to trust the government. It's a shame we don't have a choice though.",
          "My friends often invite me to go hunting with them, but I find the activty highly weird and uncomfortable. I wonder if this is how people see my Uno obsession.",
          "Recently, I've completely stopped watching the news. Why are they always so keen on making people stress?",
          "I founded an Uno club in my high school when I was 16. We had a total of 4 members, the minimum required. Only two of us were strategic. I wonder where they are now...",
          "My dad was a massive baseball fan. He actually named me after Al Oliver.",
          "The family I come from was very poor. I actually bought my first uno deck with money I made from working myself.",
          "Despite the poorness of my family growing up, I was always as happy as a curious teen could be. All thanks to my mom.",
          "Uno makes me very happy, but of course there are other things that make me happier. I wonder if there is a measurement of happiness and how it works.",
          "I got pulled over 3 weeks ago. I had to pay a fine despite only going 5 miles over the limit... And the worst part is that I still arrived to my destination late.",
          "I was never interested in history growing up. Now I've started growing curious of it. I wish I studied in school.",
          "My dad wanted me to be a professional baseball player. I definitely didn't! Active sports are so not for me! I'm more of a board game guy.",
          "I've been trying to teach my dog Uno. He's more interested in birdwatching, but I'm not giving up yet.",
          "Sometimes I wonder if I should have pursued writing instead of teaching. I've got a half-finished novel sitting in my desk drawer.",
          "I keep an Uno deck in my car. You'd be surprised how often it comes in handy during long waits.",
          "My youngest daughter rolled her eyes when I suggested Uno for family game night. It stung a bit, I'll admit.",
          "I've been thinking about starting a blog about classic card games. Maybe it'll help me connect with other enthusiasts.",
          "Last week, I found an old photo of me playing Uno with my dad. It brought back a lot of memories.",
          "I tried introducing Uno to my family at thanksgiving. It didn't go over well... they preferred arguing about politics.",
          "Sometimes I feel like the world is moving too fast. Uno helps me slow down and enjoy the moment.",
          "I've been considering volunteering at the local senior center. Maybe I could start an Uno club there.",
          "My wife says I talk about Uno too much. I'm working on expanding my conversation topics.",
          "I miss the simplicity of the 90s. Everything seemed less complicated back then, even Uno strategies.",
          "I've been trying to convince the principal at the school I teach to let me start an after-school Uno club. No luck so far.",
          "Sometimes I think about how different my life would be if I had pursued my childhood dream of becoming an actor.",
          "I've been having trouble sleeping lately. I often find myself shuffling Uno cards to relax my mind.",
          "My coworkers tease me about my Uno obsession, but I think they're just jealous of my skills.",
          "I've been thinking about my legacy lately. Will I be remembered as the 'Uno guy' or the dedicated teacher?",
          "I tried to get my brother interested in Uno, but he's more of a poker man. We don't have much in common these days.",
          "Sometimes I worry that I'm not as close to my kids as I should be. It makes me sad.",
          "I've been having some back pain recently. Getting older isn't all it's cracked up to be.",
          "I keep meaning to start exercising more, but somehow I never get to it.",
          "My high school reunion is coming up. I'm debating whether to go or not... I'm not sure I want to face those old memories.",
          "I've been thinking about taking a summer road trip. My wife really deserves the break.",
          "Sometimes I regret not traveling more when I was younger. Now I've got too many responsibilities to just pick up and go.",
          "Sometimes I wonder if I'm a good teacher at all.",
          "I've been feeling a bit restless in my career lately. But at my age, is it too late for a change?",
          "My wife suggested we try couples therapy. I'm not sure what to make of it.",
          "I've been thinking about my own mortality more often these days. I wonder if that's just part of getting older.",
          "Sometimes I feel like I'm stuck in a routine. Wake up, teach, play Uno, sleep, repeat.",
          "I've been trying to cut down on my coffee intake, but at my age you need all the energy that you can get.",
          "Lately, I've been wondering if I've made a difference in my students' lives. I hope I've inspired at least a few of them."]
         }
